dist: trusty
language: ruby
sudo: required

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - chromium-browser=57.0.2987.98-0ubuntu1.1348

before_script:
  - cp .env.example .env
  - bundle --without development production
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - bundle exec rspec spec/features/viewing_metrics_spec.rb
