dist: trusty
language: ruby
sudo: required

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_script:
  - cp .env.example .env
  - bundle --without development production
  - wget http://chromedriver.storage.googleapis.com/2.27/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo cp chromedriver /usr/local/bin/.
  - sudo chmod +x /usr/local/bin/chromedriver
  - /usr/local/bin/chromedriver --version
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - bundle exec rspec spec/features/viewing_metrics_spec.rb
